<template>
  <div class="BlogSection">
    <section class="latest-blog-section p-3 p-lg-5">
    <div class="container">
      <h2 class="section-title font-weight-bold mb-5">Latest Blog Posts</h2>
      <div class="row">
        <div class="col-md-4 mb-5">
          <div class="card blog-post-card">
            <img class="card-img-top" src="assets/images/blog/blog-post-thumb-card-1.jpg" alt="image">
            <div class="card-body">
              <h5 class="card-title"><a class="theme-link" href="blog-post.html">Top 3 JavaScript Frameworks</a></h5>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient...</p>
              <p class="mb-0"><a class="more-link" href="blog-post.html">Read more &rarr;</a></p>
              
            </div>
            <div class="card-footer">
              <small class="text-muted">Published 2 days ago</small>
            </div>
          </div><!--//card-->
        </div><!--//col-->
        <div class="col-md-4 mb-5">
          <div class="card blog-post-card">
            <img class="card-img-top" src="assets/images/blog/blog-post-thumb-card-2.jpg" alt="image">
            <div class="card-body">
              <h5 class="card-title"><a class="theme-link" href="blog-post.html">About Remote Working</a></h5>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient...</p>
              <p class="mb-0"><a class="more-link" href="blog-post.html">Read more &rarr;</a></p>
            </div>
            <div class="card-footer">
              <small class="text-muted">Published a week ago</small>
              
            </div>
          </div><!--//card-->
        </div><!--//col-->
        <div class="col-md-4 mb-5">
          <div class="card blog-post-card">
            <img class="card-img-top" src="assets/images/blog/blog-post-thumb-card-3.jpg" alt="image">
            <div class="card-body">
              <h5 class="card-title"><a class="theme-link" href="blog-post.html">A Guide to Becoming a Full-Stack Developer</a></h5>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient...</p>
              <p class="mb-0"><a class="more-link" href="blog-post.html">Read more &rarr;</a></p>
            </div>
            <div class="card-footer">
              <small class="text-muted">Published 3 weeks ago</small>
            </div>
          </div><!--//card-->
        </div><!--//col-->
      </div><!--//row-->
      <div class="text-center py-3"><a href="blog-home.html" class="btn btn-primary"><i class="fas fa-arrow-alt-circle-right mr-2"></i>View Blog</a></div>
    </div><!--//container-->
    
  </section><!--//latest-blog-section-->
  </div>
</template>
